apiVersion: messaging.knative.dev/v1alpha1
kind: Choice
metadata:
  name: check-assignment-choice
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: InMemoryChannel
  cases:
  - filter:
      ref:
        apiVersion: serving.knative.dev/v1alpha1
        kind: Service
        name: check-data-assigned
    subscriber:
      ref:
        apiVersion: serving.knative.dev/v1alpha1
        kind: Service
        name: send-message
  - filter:
      ref:
        apiVersion: serving.knative.dev/v1alpha1
        kind: Service
        name: check-data-not-assigned
    subscriber:
      ref:
        apiVersion: serving.knative.dev/v1alpha1
        kind: Service
        name: wait-assignment
  # optional reply
  # reply: