apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: istio-ingress
spec:
  tls:
    - hosts:
        - kube-dev-677874-cabc0de2dead38d7e19d28f77f8d6b64-0000.us-south.containers.appdomain.cloud
      secretName: kube-dev-677874-cabc0de2dead38d7e19d28f77f8d6b64-0000
  rules:
    - host: kube-dev-677874-cabc0de2dead38d7e19d28f77f8d6b64-0000.us-south.containers.appdomain.cloud
      http:
        paths:
          - path: /
            backend:
              serviceName: istio-ingressgateway
              servicePort: 80
