apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CronJobSource
metadata:
  name: issue-1986
spec:
  schedule: "*/1 * * * *"
  data: '{"msg":"boo"}'
  sink:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: InMemoryChannel
    name: issue-1986
  resources:
    limits:
      cpu: 25m
      memory: 50Mi
    requests:
      cpu: 25m
      memory: 50Mi