apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: issue-1986
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display