apiVersion: sources.knative.dev/v1alpha2
kind: PingSource
metadata:
  name: hello-every-second
spec:
  schedule: "* * * * * *"
  jsonData: '{"msg": "hello"}'
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
