apiVersion: sources.knative.dev/v1beta2
kind: PingSource
metadata:
  name: ping-source-2
spec:
  schedule: "*/1 * * * *"
  data: "Hello world from 2!"
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: broker
