apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-1
spec:
  broker: broker
  filter:
    attributes:
      knsource: ping-source-1.pingsources.sources.knative.dev
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display-1
