apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: print-host
  namespace: examples-mtksvc
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: ../src/printhost
