apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: products-3
spec:
  consumerGroup: products-3-group
  consumers: 100
  bootstrapServers:
    - my-cluster-kafka-bootstrap.kafka:9092
  topics:
    - products
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
