language: go
go:
  - 1.12.x
sudo: required
dist: xenial
addons:
  snaps:
    - name: kubectl
      confinement: classic
    - name: helm
      confinement: classic
    - name: node
      channel: "8/stable"
      confinement: classic

branches:
  only:
    - "master"

install: skip

before_script:
  - sudo mv bin/linux/amd64/kind /usr/local/bin
  - go get github.com/ibm/kone/cmd/kone

jobs:
  include:
  - install: skip
    name: "Serving 0.12.0 / Eventing 0.12.0"
    script:
    - test/e2e.sh 0.12.0 0.12.0
  - install: skip
    name: "Serving 0.13.2 / Eventing 0.13.6"
    script:
    - test/e2e.sh 0.13.2 0.13.6
  - install: skip
    name: "Serving nightly / Eventing nightly"
    script:
    - test/e2e.sh nightly nightly

