sudo: required
dist: xenial
addons:
  snaps:
    - name: kubectl
      confinement: classic
    - name: helm
      confinement: classic
    - name: node
      channel: "8/stable"
      confinement: classic
    - name: go
      confinement: classic
      channel: 1.13/stable


before_script:
  - GO111MODULE="on" go get sigs.k8s.io/kind@v0.5.1
  - go get github.com/ibm/kone/cmd/kone

jobs:
  include:
  - script:
    - test/e2e.sh 0.8.1 0.8.0