dist: xenial
addons:
  snaps:
    - name: helm
      confinement: classic

sudo: required

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config

before_script:
- bin/setup-minikube.sh

jobs:
  include:
  - script:
    - bin/setup-knative-minikube.sh 0.8.1 0.8.0