language: go
go:
  - 1.12.x
sudo: required
dist: xenial
addons:
  snaps:
    - name: kubectl
      confinement: classic
    - name: helm
      confinement: classic
    - name: node
      channel: "8/stable"
      confinement: classic

install: skip

before_script:
  - sudo mv bin/linux/amd64/kind /usr/local/bin
  - go get github.com/ibm/kone/cmd/kone

jobs:
  include:
  - install: skip
    name: "Serving 0.8.1 / Eventing 0.8.0"
    script:
    - test/e2e.sh 0.8.1 0.8.0
  - install: skip
    name: "Serving 0.9.0 / Eventing 0.9.0"
    script:
    - test/e2e.sh 0.9.0 0.9.0
  - install: skip
    name: "Serving 0.10.0 / Eventing 0.10.0"
    script:
    - test/e2e.sh 0.10.0 0.10.0
  - install: skip
    name: "Serving 0.10.0 / Eventing nightly"
    script:
    - test/e2e.sh 0.10.0 nightly
  - install: skip
    name: "Unit testing"
    script:
    - test/src/function.sh