language: go
sudo: required
dist: xenial
addons:
  snaps:
    - name: helm
      confinement: classic
    - name: microk8s
      confinement: classic
    - name: node
      channel: "8/stable"
      confinement: classic

# env:
#   global:
#     - CHANGE_MINIKUBE_NONE_USER=true
#     - MINIKUBE_WANTUPDATENOTIFICATION=false
#     - MINIKUBE_WANTREPORTERRORPROMPT=false
#     - MINIKUBE_HOME=$HOME
#     - CHANGE_MINIKUBE_NONE_USER=true
#     - KUBECONFIG=$HOME/.kube/config

before_script:
  - sudo microk8s.status --wait-ready
  - sudo snap alias microk8s.kubectl kubectl
  - sudo ls -la /snap/microk8s/current
  - sudo microk8s.enable knative
  - sudo microk8s.status
  - go get github.com/ibm/kone/cmd/kone
  #- bin/setup-minikube.sh

# jobs:
#   include:
#   - script:
#     - n/setup-knative-minikube.sh 0.8.1 0.8.0