language: go
sudo: required
dist: xenial
addons:
  snaps:
    - name: kubectl
      confinement: classic
    - name: helm
      confinement: classic
    # - name: microk8s
    #   confinement: classic
    - name: node
      channel: "8/stable"
      confinement: classic

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config

before_script:
  # - GO111MODULE="on" go get sigs.k8s.io/kind@v0.5.1
  - go get github.com/ibm/kone/cmd/kone
  - bin/setup-minikube.sh

jobs:
  include:
  - script:
    - bin/setup-knative-minikube.sh 0.8.1 0.8.0 # bin/setup-knative-kind.sh 0.8.1 0.8.0