apiVersion: bindings.knative.dev/v1beta1
kind: KafkaBinding
spec:
  bootstrapServers:
    - broker-5-nxgt7l9rxcqqxvxm.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093
  net:
    sasl:
      enable: true
      user:
        secretKeyRef:
          name: secret-eventstream
          key: user
      password:
        secretKeyRef:
          name: secret-eventstream
          key: password
  subject:
    apiVersion: KafkaSouce
