apiVersion: messaging.knative.dev/v1alpha1
kind: Parallel
metadata:
  name: check-assignment
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: InMemoryChannel
  branches:
  - filter:
      ref:
        apiVersion: serving.knative.dev/v1alpha1
        kind: Service
        name: check-data-assigned
    subscriber:
      ref:
        apiVersion: serving.knative.dev/v1alpha1
        kind: Service
        name: send-message
  - filter:
      ref:
        apiVersion: serving.knative.dev/v1alpha1
        kind: Service
        name: check-data-not-assigned
    subscriber:
      ref:
        apiVersion: serving.knative.dev/v1alpha1
        kind: Service
        name: wait-assignment
