apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: products
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1000
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
