apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: assign-photographer
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: InMemoryChannel
    name: assign-photographer
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: assign-photographer
  delivery:
    deadLetterSink:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: assign-photographer-deadletter

