apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: products
spec:
  consumerGroup: products-group
  topics:
    - products
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
