apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CronJobSource
metadata:
  name: minute
spec:
  schedule: "* * * * *"
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Broker
    name: default