apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: ns
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
    name: ns
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display-ns
