apiVersion: sources.knative.dev/v1beta2
kind: PingSource
metadata:
  name: default
spec:
  schedule: "*/1 * * * *"
  data: default
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: InMemoryChannel
      name: default
