apiVersion: v1
kind: ServiceAccount
metadata:
  name: apiserversource-example
  namespace: apiserversource-example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apiserversource-example
rules:
  - apiGroups:
      - serving.knative.dev
    resources:
      - revisions
    verbs: # The source only need get, list and watch
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apiserversource-example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apiserversource-example
subjects:
  - kind: ServiceAccount
    name: apiserversource-example
    namespace: apiserversource-example