apiVersion: sources.knative.dev/v1alpha2
kind: ApiServerSource
metadata:
  name: revision
  namespace: apiserversource-example
spec:
  serviceAccountName: apiserversource-example
  mode: Reference
  resources:
  - apiVersion: serving.knative.dev/v1
    kind: Revision
  sink:
   ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: event-display
