apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: istio-ingress
  namespace: istio-system
spec:
  rules:
  - host: '*.kne-dev-cabc0de2dead38d7e19d28f77f8d6b64-0000.us-south.containers.appdomain.cloud'
    http:
      paths:
      - path: /
        backend:
          serviceName: istio-ingressgateway
          servicePort: 80

