apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
# - role: control-plane
- role: control-plane
  extraPortMappings:
  - containerPort: 31380 # istio-ingressgateway
    hostPort: 8080
    listenAddress: "127.0.0.1"
  - containerPort: 9092 # Kafka
    hostPort: 9092

