kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 31380 # istio-ingressgateway
    hostPort: 8080
    listenAddress: "127.0.0.1"