apiVersion: batch/v1
kind: Job
metadata:
  name: event-sender
spec:
  template:
    spec:
      containers:
      - name: event-sender
        image: docker.io/knativeexamples/event-sender
        args:
          - '-sink=http://kafka-sink-ingress.knative-eventing.svc.cluster.local/sources-kafka-keda/products'
          - '-event={"specversion":"1.0", "source":"event-sender", "type" : "event-sender"}'
          - '-period=100'
          - '-delay=100'
          - '-incremental-id=true'
          - '-max-messages=0'
      restartPolicy: Never
