apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: products
#  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 10
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
