apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: trigger-1
spec:
  broker: broker
  filter:
    attributes:
      type: dev.knative.source.github.issues
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display-1
