apiVersion: messaging.knative.dev/v1beta1
kind: KafkaChannel
metadata:
  name: products
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-mycluster
  numPartitions: 1
  replicationFactor: 1
