apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-counter
spec:
  selector:
    matchLabels:
     app: event-counter
  template:
    metadata:
      labels:
        app: event-counter
    spec:
      containers:
      - name: event-counter
        image: ../../../../src/event-counter
        env:
        - name: P_SECONDS
          value: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: event-counter
spec:
  selector:
    app: event-counter
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
