apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wait
spec:
  template:
    spec:
      containers:
        - image: ../../../../src/wait
          env:
            - name: P_SECONDS
              value: "10"
