apiVersion: sources.knative.dev/v1alpha2
kind: PingSource
metadata:
  name: add-product
spec:
  schedule: "*/1 * * * *"
  jsonData: '{"brand":"POLO RALPH LAUREN", "name": "Polo Ralph Lauren 3-Pack Socks", "category": "Socks for Men"}'
  sink:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Sequence
      name: acquire-photo
