apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: routing-assigned
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: InMemoryChannel
    name: test-routing
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: routing-assigned
