apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: data-assigned
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: InMemoryChannel
    name: data-assigned
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: send-message

