apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ApiServerSource
metadata:
  name: revision
  namespace: apiserversource-example
spec:
  serviceAccountName: apiserversource-example
  mode: Ref
  resources:
  - apiVersion: serving.knative.dev/v1alpha1
    kind: Revision
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: event-display