apiVersion: sources.knative.dev/v1alpha2
kind: PingSource
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jsonData: '{"msg": "hello"}'
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
