apiVersion: sources.knative.dev/v1alpha2
kind: PingSource
metadata:
  name: ping-timezone
spec:
  schedule: "CRON_TZ=GMT */1 * * * *"
  jsonData: '{"msg": "hello"}'
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
