apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: record-assignment
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: InMemoryChannel
    name: wait-photo
  subscriber:
    ref:
      apiVersion: messaging.knative.dev/v1alpha1
      kind: Sequence
      name: record-assignment

