apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: hello-no-wrapper
spec:
  schedule: "*/1 * * * *"
  data: "hello"
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
