apiVersion: batch/v1
kind: Job
metadata:
  name: event-sender-products
spec:
  template:
    spec:
      containers:
      - name: event-sender
        image: ko://github.com/lionelvillard/knative-examples/test/images/event-sender
        args:
          - '-sink=http://kafka-sink-ingress.knative-eventing.svc.cluster.local/{{.Namespace}}/products'
          - '-event={"specversion":"1.0", "source":"event-sender-products", "type" : "event-sender-products"}'
          - '-period=1000'
          - '-delay=200'
          - '-incremental-id=true'
          - '-max-messages=0'
      restartPolicy: Never
