apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-2-svc
spec:
  selector:
    matchLabels:
      app: server-2-svc
  template:
    metadata:
      labels:
        app: server-2-svc
    spec:
      containers:
        - name: app
          image: ko://http/limits/cmd/server
          args:
            - "--count=2"
---
apiVersion: v1
kind: Service
metadata:
  name: server-2-svc
spec:
  selector:
    app: server-2-svc
  ports:
    - name: m
      port: 9000
    - name: p50000
      port: 50000
    - name: p50001
      port: 50001
