apiVersion: sources.knative.dev/v1alpha2
kind: PingSource
metadata:
  name: hello-xml
spec:
  schedule: "*/1 * * * *"
  jsonData: '<element attr="boo"></element>'
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
