apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: products
spec:
  consumerGroup: knative-group
  bootstrapServers:
    - does-not-exist.kafka:9092
  topics:
    - products
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
