apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: products
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    name: products
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display

