apiVersion: sources.knative.dev/v1beta1
kind: PingSource
metadata:
  name: hello-unique-name
spec:
  schedule: "*/1 * * * *"
  jsonData: '{"msg": "hello"}'
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
