apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: check-data-assigned
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: InMemoryChannel
    name: check-assignment
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: check-data-assigned
  reply:
    channel:
      apiVersion: messaging.knative.dev/v1alpha1
      kind: InMemoryChannel
      name: data-assigned
