apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: data-not-assigned
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: InMemoryChannel
    name: data-not-assigned
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: wait-assignment

