name: KinD e2e tests

on:
  push:
    branches:
    - main

  schedule:
  - cron: '0 */4 * * *'

  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./src/github.com/lionelvillard/knative-examples

jobs:
  e2e-tests:
    name: e2e tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - ./examples/sources/kafka/sanity

    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
      KO_DOCKER_REPO: kind.local
      TERM: xterm-256color

    steps:
    - name: testing
      working-directory: ./
      run: |
        tags=
        echo "${tags:-}"
        
    - name: Set up Go 1.15.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - name: Install Dependencies
      working-directory: ./
      run: |
        GO111MODULE=on go get github.com/google/ko/cmd/ko@master

    - name: Check out code onto GOPATH
      uses: actions/checkout@v2
      with:
        path: ./src/github.com/lionelvillard/knative-examples

   

    - name: Install KinD
      run: |
        set -x

        # Disable swap otherwise memory enforcement doesn't work
        # See: https://kubernetes.slack.com/archives/CEKK1KTN2/p1600009955324200
        sudo swapoff -a
        sudo rm -f /swapfile

        curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.9.0/kind-$(uname)-amd64
        chmod +x ./kind
        sudo mv kind /usr/local/bin

    - name: Start KinD
      run: |
        cd  ${{ matrix.test }}
        [[ -f "0-start-kind.sh" ]] && ./0-start-kind.sh

    - name: Run e2e Tests
      run: |
        cd  ${{ matrix.test }}
        echo running test in ${{ matrix.test }}
        [[ -f "1-setup-cluster.sh" ]] && ./1-setup-cluster.sh
        [[ -f "3-deploy.sh" ]] && ./3-deploy.sh
        [[ -f "4-test.sh" ]] && ./4-test.sh

    - name: Upload artifacts
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-log
        path: /tmp/log.*
