name: dispatch

on:  
 workflow_dispatch:


jobs:
  notify:
    name: Repository Dispatch
    runs-on: ubuntu-latest
    steps:
    - name: testing
      shell: bash
      run: |
        tags=
        echo "${tags}"
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: lionelvillard/eventing-kafka-testing
        event-type: pr
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
